ktor {
    deployment {
        environment = prod
        port = 8080
    }

    application {
        modules = [ com.bashkevich.ApplicationKt.module
        ]
    }
}

telegram-bot {
    token = ${TELEGRAM_BOT_TOKEN}
    username = ${TELEGRAM_BOT_USERNAME}
}
